version: '3.3'
services:
  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    ports:
      - "8024:8080"
    environment:
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      - KEYCLOAK_IMPORT=/tmp/import/keep-growing-realm.json
    volumes:
      - ./keycloak/realms/import/keep-growing-realm.json:/tmp/import/keep-growing-realm.json
      - ./keycloak/realms/export:/tmp/export
